# Load libraries
```{r}
library(tidyverse)
library(here)
library(patchwork)
```
# Load data
```{r}
source("load_tables.R")
source("load_plot_aesthetics.R")
```

# Figure 2 - nonHLA figures

```{r}
nonhla_count <- table_s2 %>%
  select(-orf_biotype) %>%
  inner_join(orf_sequences %>%
               select(orf_name, orf_biotype), "orf_name") %>%
  dplyr::count(orf_name, orf_biotype) %>%
  group_by(orf_biotype) %>%
  summarise(n_pep = sum(n), n_orf_1 = sum(n == 1), n_orf_2 = sum(n >= 2)) %>%
  pivot_longer(c(n_orf_1, n_orf_2, n_pep)) %>%
  mutate(
    x_label = str_replace_all(name, "_\\d", ""),
    name = factor(name, levels = c("n_pep", "n_orf_2", "n_orf_1"))
  ) %>%
  make_biotype_levels()

nonhla_count_group <- nonhla_count %>%
  filter(name != "n_pep") %>%
  group_by(name) %>%
  summarise(value = sum(value))

val_count <- nonhla_count %>%
  dplyr::count(name, wt = value) %>%
  inner_join(data.frame(name = c("n_orf_2", "n_orf_1"),
                        n_val = c(30, 36)), "name") %>%
  mutate(n_nonval = n - n_val) %>%
  select(-n) %>%
  column_to_rownames("name") %>%
  t() %>%
  data.frame() %>%
  rownames_to_column("label") %>%
  mutate(
    ypos2 = cumsum(n_orf_2) - 0.5 * n_orf_2,
    ypos1 = cumsum(n_orf_1) - 0.5 * n_orf_1
  )

nonhla_pep_count <- table_s3 %>%
  filter(HPP.Category %in% c("HPP+", "1PepCandidate")) %>%
  mutate(
    n_pep = ifelse(n_peptides_in_entry > 4, ">4", n_peptides_in_entry),
    n_pep = factor(n_pep, c(1, 2, 3, 4, ">4"))
  ) %>%
  dplyr::count(n_pep)

figure_2A <- ggplot() +
  geom_bar(
    data = nonhla_count %>% filter(name == "n_pep"),
    aes(x = orf_biotype, y = value, fill = name),
    stat = "identity", show.legend = F
  ) +
  scale_x_discrete(name = element_blank(), expand = c(0, 0)) +
  scale_y_continuous(name = "Number of peptides", expand = c(0, 0)) +
  scale_fill_manual(values = blue_col[3]) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

figure_2B1 <- ggplot() +
  geom_bar(
    data = nonhla_count %>% filter(name != "n_pep"),
    aes(x = orf_biotype, y = value, fill = name),
    stat = "identity", position = "stack"
  ) +
  scale_x_discrete(name = element_blank(), expand = c(0, 0)) +
  scale_y_continuous(name = "Number of ncORFs", expand = c(0, 0)) +
  scale_fill_manual(
    values = green_col[c(6, 1)],
    labels = c(
      "Multiple peptide detections",
      "Single peptide detections"
    ),
    name = element_blank()
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

figure_2B2 <- ggplot() +
  geom_bar(
    data = nonhla_count_group,
    aes(x = "", y = value, fill = name),
    stat = "identity", position = "stack", show.legend = F
  ) +
  scale_x_discrete(name = element_blank(), expand = c(0, 0)) +
  scale_y_continuous(name = "Number of ncORFs", expand = c(0, 0)) +
  scale_fill_manual(values = green_col[c(6, 1)]) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.ticks.x = element_blank()
  )

figure_2C1 <- ggplot(val_count, aes(x = "", y = n_orf_2, fill = label)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0, direction = 1) +
  theme_void() +
  theme(legend.text = element_text(size = 7, colour = "black")) +
  geom_text(aes(y = ypos2, label = n_orf_2), color = "black", size = 7 / .pt) +
  scale_fill_manual(
    values = c(pink_col[4], green_col[4]),
    name = element_blank(),
    labels = c(
      "Insufficient\nevidence",
      "Passing\ninspection"
    )
  )

figure_2C2 <- ggplot(val_count, aes(x = "", y = n_orf_1, fill = label)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0, direction = 1) +
  theme_void() +
  theme(legend.text = element_text(size = 7, colour = "black")) +
  geom_text(aes(y = ypos1, label = n_orf_1), color = "black", size = 7 / .pt) +
  scale_fill_manual(
    values = c(pink_col[4], green_col[4]),
    name = element_blank(),
    labels = c(
      "Insufficient\nevidence",
      "Passing\ninspection"
    )
  )

figure_2D <- ggplot(nonhla_pep_count, aes(y = n, x = n_pep)) +
  geom_bar(
    position = "stack", stat = "identity", show.legend = F,
    fill = green_col[4]
  ) +
  scale_x_discrete(name = "Number of distinct peptides", expand = c(0, 0)) +
  scale_y_continuous(name = "Number of non-canonical ORFs", expand = c(0, 0)) +
  geom_text(aes(label = n), size = 6 / .pt)

figure_2 <- figure_2A + figure_2B1 + figure_2B2 + (figure_2C1 / figure_2C2) +
  figure_2D + plot_layout(guides = "collect", widths = c(7, 7, 1, 10, 5))

ggsave("Figure_2.svg",
  device = "svg", path = plot_dir, figure_2,
  width = 2600, height = 900, units = "px"
)
```


